import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Generated by Antigravity (Manual Migration to School Management App).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5nJPIY8l6-xSavGdi1jgpwaBH1E4HX4w',
    appId: '1:298200431847:web:39c81bd36502a41aaa3642',
    messagingSenderId: '298200431847',
    projectId: 'gen-lang-client-0167429912',
    authDomain: 'gen-lang-client-0167429912.firebaseapp.com',
    storageBucket: 'gen-lang-client-0167429912.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGR282U_i9V2XmxMCRUMfJN_w9_WSzCF0',
    appId: '1:298200431847:android:84e695ae9cf1cafcaa3642',
    messagingSenderId: '298200431847',
    projectId: 'gen-lang-client-0167429912',
    storageBucket: 'gen-lang-client-0167429912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGR282U_i9V2XmxMCRUMfJN_w9_WSzCF0',
    appId: '1:298200431847:ios:placeholder',
    messagingSenderId: '298200431847',
    projectId: 'gen-lang-client-0167429912',
    storageBucket: 'gen-lang-client-0167429912.firebasestorage.app',
    iosBundleId: 'com.example.schoolManagementApp',
  );
}
